import mongoose from "mongoose";

const imageSchema = new mongoose.Schema(
  {
    refNo: {
      type: String,
      required: true,
      index: true,
    },

    filename: {
      type: String,
      required: true,
    },

    folderName: {
      type: String,
      required: true,
    },

    content_type: {
      type: String,
      required: true,
    },

    image_url: {
      type: String,
      required: true,
    },

    // Progressive loading URLs (optional — generated by upload pipeline)
    thumb_res_url: {
      type: String,
      default: null,
    },
    low_res_url: {
      type: String,
      default: null,
    },

    // Dimensions for aspect-ratio locking (optional — older images may not have these)
    width: {
      type: Number,
      default: null,
    },
    height: {
      type: Number,
      default: null,
    },

    event_name: {
      type: String,
      required: true,
    },
    embeddings: {
      type: [Number], // Clean numeric array
      required: true,
    },

    fileSize: {
      type: Number,
      default: 0,
    },
    additionalFolders: {
      type: [String],
      default: [],
    },
    // Blurhash for faster perceived loading
    blurhash: {
      type: String,
      default: null,
    },
    // Client favorites - array of client emails who liked this image
    likedByClients: {
      type: [String],
      default: [],
    },
    // Owner/studio favorite - whether project owner liked this image
    likedByOwner: {
      type: Boolean,
      default: false,
    },
    tags: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);


export default mongoose.model("Images", imageSchema, "Images");